apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: team-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: premium-ssd
  resources:
    requests:
      storage: 10Gi
