apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-role-binding
  namespace: team-dev
subjects:
- kind: ServiceAccount
  name: dev-user
  namespace: team-dev
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io
