apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secret
  namespace: team-dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: ""
    objects: |
      array:
        - |
          objectName: database-password
          objectType: secret
    tenantId: aa9e71e9-ffd0-4b8f-8b75-b7e6c5dd880e
